Added more errors!
Tjerk258/vesofton_otd pull request #13
Opened 2022-05-19 07:42 UTC by Shariefie

Check the errors

2022-05-19 09:47 UTC, Tjerk258 requested changes
ziet er goed uit alleen error functie moet in logic_layer aangeroepen worden

2022-05-19 09:47 UTC, Tjerk258 commented on Core/Src/API.c
>  #endif
geen ifdef wel endif?

2022-05-19 09:47 UTC, Tjerk258 commented on Core/Src/main.c
> +  //drawText(0, 20, VGA_COL_BLUE, "ABCDEFGHIJKL", "Arials", 1, 1);
Onnodige comments

2022-05-19 10:05 UTC, bestehustudentEU reviewed
see comments

2022-05-19 10:05 UTC, bestehustudentEU commented on Core/Inc/API.h
> +#define MAX_FIGURE_POINTS		10
this define is not needed.

2022-05-19 10:05 UTC, bestehustudentEU commented on Core/Inc/error.h
> +#define ERROR_BITMAP_NOT_FOUND				1
defines has diference spacing.

2022-05-19 10:05 UTC, bestehustudentEU commented on Core/Src/API.c
> +	if((x_begin < 0) || (y_begin < 0) || (x_eind > VGA_DISPLAY_X) || (y_eind < VGA_DISPLAY_Y))
not 100%, x_begin,y_begin can be higher than display and x_eind ,y_eind can be lower than zero

2022-05-19 10:05 UTC, bestehustudentEU commented on Core/Src/API.c
> +	if(x_begin < 0x00)
define forgotten.

2022-05-19 10:05 UTC, bestehustudentEU commented on Core/Src/API.c
> +	if(((x_begin+x_eind) > VGA_DISPLAY_X) || ((y_begin+y_eind) > VGA_DISPLAY_Y))
? do the same as my tekenaar.

2022-05-19 10:05 UTC, bestehustudentEU commented on Core/Src/API.c
> +	if (lijn_dikte > LINE_WIDTH)
smaller than, not needed?

2022-05-19 10:05 UTC, bestehustudentEU commented on Core/Src/API.c
> +	if(((x_pos+length) > VGA_DISPLAY_X) || ((y_pos+width) > VGA_DISPLAY_Y) || ((x_pos+length) < VGA_DISPLAY_X) || ((y_pos+width) < VGA_DISPLAY_Y))
compleet fout!
(x_pos+length) groter of lager dan vga display?

2022-05-19 10:05 UTC, bestehustudentEU commented on Core/Src/API.c
> +
why did you add spacing?

2022-05-19 10:05 UTC, bestehustudentEU commented on Core/Src/API.c
> +		{
why did you add curly brackets?

2022-05-19 10:05 UTC, bestehustudentEU commented on Core/Src/API.c
> +	void drawCircle(uint16_t x_pos, uint16_t y_pos, uint8_t radius, uint8_t kleur)
spacing?

2022-05-19 10:05 UTC, bestehustudentEU commented on Core/Src/main.c
> +  //drawText(0, 0, VGA_COL_BLUE, "ABCDEFGHIJKL", "Consolas", 0, 0);
delete comment

2022-05-19 10:13 UTC, Shariefie commented on Core/Src/API.c
>  #endif
Solved!

2022-05-19 10:13 UTC, Shariefie commented on Core/Src/main.c
> +  //drawText(0, 20, VGA_COL_BLUE, "ABCDEFGHIJKL", "Arials", 1, 1);
Deleted

2022-05-19 10:15 UTC, Shariefie commented on Core/Inc/API.h
> +#define MAX_FIGURE_POINTS		10
Solved!

2022-05-19 10:18 UTC, Shariefie commented on Core/Inc/error.h
> +#define ERROR_BITMAP_NOT_FOUND				1
Solved!

2022-05-19 10:24 UTC, Shariefie commented on Core/Src/API.c
> +	if(x_begin < 0x00)
This is your own code written!!

2022-05-19 10:24 UTC, Shariefie commented on Core/Src/API.c
> +	if(x_begin < 0x00)
But i solved it!

2022-05-19 10:26 UTC, Shariefie commented on Core/Src/API.c
> +	if(((x_begin+x_eind) > VGA_DISPLAY_X) || ((y_begin+y_eind) > VGA_DISPLAY_Y))
Solved!

2022-05-19 10:29 UTC, Shariefie commented on Core/Src/API.c
> +	if(((x_pos+length) > VGA_DISPLAY_X) || ((y_pos+width) > VGA_DISPLAY_Y) || ((x_pos+length) < VGA_DISPLAY_X) || ((y_pos+width) < VGA_DISPLAY_Y))
Solved!

2022-05-19 10:31 UTC, Shariefie commented on Core/Src/API.c
> +
I did not add space, github issue i guess!

2022-05-19 10:32 UTC, Shariefie commented on Core/Src/API.c
> +		{
Nothing found, github issue.

2022-05-19 10:33 UTC, Shariefie commented on Core/Src/API.c
> +	void drawCircle(uint16_t x_pos, uint16_t y_pos, uint8_t radius, uint8_t kleur)
Nothing found.....

2022-05-19 10:34 UTC, Shariefie commented on Core/Src/main.c
> +  //drawText(0, 0, VGA_COL_BLUE, "ABCDEFGHIJKL", "Consolas", 0, 0);
deleted already..

2022-05-19 11:07 UTC, Tjerk258 approved these changes

2022-05-24 11:13 UTC, bestehustudentEU approved these changes

2022-05-24 11:25 UTC, merged