draw commando's
Tjerk258/vesofton_otd pull request #7
Opened 2022-05-17 17:36 UTC by bestehustudentEU

pull!

2022-05-17 17:47 UTC, Tjerk258 requested changes
Spellingsfouten en geen consistentie in spaties

2022-05-17 17:47 UTC, Tjerk258 commented on Core/Src/API.c
> +		printf("waarde is %d\n", lijn_dikte);
Welke waarde?

2022-05-17 17:47 UTC, Tjerk258 commented on Core/Src/API.c
> +	int figure_ram_x[nr_pointsgiven]; // Array where the loop can easy find the x coordinates
can easily find

2022-05-17 18:06 UTC, Shariefie reviewed
Verbeter de kleine spellingfouten, dit komt voornamelijk voor in het eerste gedeelde. De rest ziet er goed uit. Netjes gewerkt.

2022-05-17 18:06 UTC, Shariefie commented on Core/Inc/API.h
> +#include <stdio.h>
Hier moeten de gegevens van de auteur en de file komen.

2022-05-17 18:06 UTC, Shariefie commented on Core/Inc/API.h
> + * @details This function starts with 5 variables, x and y coordinate for the begin and coordinates for the end.
coordinates for begin and the end.

2022-05-17 18:06 UTC, Shariefie commented on Core/Inc/API.h
> + * 			last variable as color of the line.
The last

2022-05-17 18:06 UTC, Shariefie commented on Core/Inc/API.h
> + * 			If y offset is zero the function draws horizontal line, else a vertical line.
Spelling fouten eruit halen

2022-05-17 18:06 UTC, Shariefie commented on Core/Src/API.c
Bij elke functie in het kort uitleggen!

2022-05-17 18:06 UTC, Shariefie commented on Core/Src/API.c
> +	for (i = i; i < nr_pointsgiven*2; i++)
i = 0 en niet i = i

2022-05-17 19:39 UTC, Tjerk258 requested changes

2022-05-17 19:39 UTC, Tjerk258 commented on Core/Inc/API.h
> +void drawLines( uint16_t x_begin, uint16_t y_begin, uint16_t x_eind, uint16_t y_eind,uint8_t kleur,uint8_t lijn_dikte);
vekeerde functie benaming
draw_lines

2022-05-17 19:39 UTC, Tjerk258 commented on Core/Inc/API.h
> +void drawRect(uint16_t x_pos,uint16_t y_pos,uint16_t length,uint16_t width,uint8_t kleur,uint8_t filled);
draw_rectancle

2022-05-17 19:39 UTC, Tjerk258 commented on Core/Inc/API.h
> +void drawCircle(uint16_t x_pos, uint16_t y_pos,uint8_t radius,uint8_t kleur);
draw_circle

2022-05-17 19:39 UTC, Tjerk258 commented on Core/Inc/API.h
> +void drawFigure(uint8_t kleur,uint8_t nr_pointsgiven,...);
draw_figure

2022-05-18 15:13 UTC, bestehustudentEU commented on Core/Src/API.c
> +		printf("waarde is %d\n", lijn_dikte);
Solved.

2022-05-18 15:14 UTC, bestehustudentEU commented on Core/Inc/API.h
> +#include <stdio.h>
merge conflict

2022-05-18 15:14 UTC, bestehustudentEU commented on Core/Inc/API.h
> + * @details This function starts with 5 variables, x and y coordinate for the begin and coordinates for the end.
Solved

2022-05-18 15:15 UTC, bestehustudentEU commented on Core/Inc/API.h
> + * 			last variable as color of the line.
Solved

2022-05-18 15:16 UTC, bestehustudentEU commented on Core/Inc/API.h
> + * 			If y offset is zero the function draws horizontal line, else a vertical line.
Solved (i think).

2022-05-18 15:16 UTC, bestehustudentEU commented on Core/Src/API.c
No need

2022-05-18 15:16 UTC, bestehustudentEU commented on Core/Src/API.c
> +	for (i = i; i < nr_pointsgiven*2; i++)
Solved

2022-05-18 15:17 UTC, bestehustudentEU commented on Core/Inc/API.h
> +void drawLines( uint16_t x_begin, uint16_t y_begin, uint16_t x_eind, uint16_t y_eind,uint8_t kleur,uint8_t lijn_dikte);
Nope

2022-05-18 15:17 UTC, bestehustudentEU commented on Core/Inc/API.h
> +void drawRect(uint16_t x_pos,uint16_t y_pos,uint16_t length,uint16_t width,uint8_t kleur,uint8_t filled);
Nope

2022-05-18 15:17 UTC, bestehustudentEU commented on Core/Inc/API.h
> +void drawCircle(uint16_t x_pos, uint16_t y_pos,uint8_t radius,uint8_t kleur);
Nope

2022-05-18 15:17 UTC, bestehustudentEU commented on Core/Inc/API.h
> +void drawFigure(uint8_t kleur,uint8_t nr_pointsgiven,...);
Nope

2022-05-18 15:34 UTC, Shariefie reviewed
Verbeter de kleine spellingfouten, dit komt voornamelijk voor in het eerste gedeelde. De rest ziet er goed uit. Netjes gewerkt.

2022-05-18 15:34 UTC, Shariefie commented on Core/Src/logic_layer.c
> + *@brief	this function looks at input array and calls function the input array calls for
Begin with Capital letter.

2022-05-18 15:34 UTC, Shariefie commented on Core/Src/logic_layer.c
> + *			Then the function looks which script is called.
Grammatics

2022-05-18 15:34 UTC, Shariefie commented on Core/Src/logic_layer.c
> +	char commando_filled[10][20]; // Here is the script split into multiple array.
Defines the numbers.

2022-05-18 15:36 UTC, bestehustudentEU commented on Core/Src/logic_layer.c
> + *@brief	this function looks at input array and calls function the input array calls for
Solved.

2022-05-18 15:37 UTC, bestehustudentEU commented on Core/Src/logic_layer.c
> + *			Then the function looks which script is called.
Solved.

2022-05-18 16:20 UTC, bestehustudentEU commented on Core/Src/logic_layer.c
> +	char commando_filled[10][20]; // Here is the script split into multiple array.
solved.

2022-05-18 16:30 UTC, merged